### ISSUE TITLE
OpenVPN profile contains empty certificates

### ISSUE THREAD

**Issue by bibihub** [freedombox/Plinth#758] opened 2017-03-15 16:32 UTC
Hello 
I wanted to download my profile openvpn with plinth and when I opened it with gedit it miss the part between <cert> and </ cert>. If I create another user and I download his profile through the interface of plinth, I have no problem.
Cordially.
Thierry.

**Comment by harry-7** [comment] 2017-03-24 04:52
@SunilMohanAdapa   I want to take up this issue . Can you guide me through this.

**Comment by SunilMohanAdapa** [comment] 2017-03-24 06:47
@harry-7 Please go ahead. As discussed on the IRC, please try to reproduce the problem by creating multiple users, downloading their profile and seeing if the certificates are missing in any of the profiles.  If you are unable to reproduce the issue, then go through the code paths that could have lead to this.  Post any questions you may have that could clarify/confirm your analysis.

**Comment by harry-7** [comment] 2017-03-24 08:15
@bibihub  Can you check whether this file is present or not in the machine where your plinth is installed. If you are using vagrant then do 
`` vagrant up ``
``vagrant ssh``
 and check whether this file is present or not.
`/etc/openvpn/freedombox-keys/<user_name>.crt`
where <user_name> is the username for which you found out that the certificate is missing .

**Comment by bibihub** [comment] 2017-03-24 10:10
Since I posted the empty openvpn bug on github, the problem has been resolved. I re-install freedombox and openvpn on a rpi2 2 days ago and I did not have any profile problem.
I just looked in "/etc/openvpn /freedombox-keys" and I have my USER.crt file correctly filled in.
When I had the worry I was not thinking about looking at this file.

**Comment by SunilMohanAdapa** [comment] 2017-03-24 10:24
@harry-7 pointed to a bug in openvpn https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=328845 that could have caused the empty certificates.  However, this seems unlikely due the country, city and other details (which are not important) being hard coded to the same value in our code.

We could continue to investigate the problem.  I was thinking of potential conditions that could have lead to the problem.

- One is that during the generation of the certificates the process was interrupted. This could have lead to empty certificate files were generated.  Since our process does not question the consistency of the files if they exist, next time we are not attempting to generate them.  This could be solved by actually writing to temporary files (in the same directory) when creating them and then renaming when the generation is successfully completed.  We could also consider treating empty files as non-existent.

- Another problem could be a race condition in generating the files if multiple processes tried to generate the certificates for the same user at the same time.  This can happen for example because of a double click on the download profile button.  This can be avoided by using the lock.

**Comment by harry-7** [comment] 2017-03-24 11:34
@SunilMohanAdapa   for the first one I think second option will be better if there is an empty certificate then we treat it as non-existent and ask the user to re run the setup. Can we do that somehow ?

**Comment by SunilMohanAdapa** [comment] 2017-03-27 16:37
I have merged #769 and during testing I encountered the original bug or at least a variant of it.  When I remove the certificates for a user and try to regenerate the certificates, then the `pkitool` fails without any error code.  When run on the command line, it shows the following error:
```
failed to update database
TXT_DB error number 2
```
This seems to be due to trying to regenerate a certificate for same 'Common Name' (in our case username).  See: https://community.openvpn.net/openvpn/ticket/229 . Please try to reproduce the issue and confirm it.

Solution seems to be write `unique_subject = no` in `index.txt.attr` file so that duplicate certificates can be generated for a give user.  

@harry-7 , please work on implementing this solution next to close this issue.

**Comment by harry-7** [comment] 2017-03-28 07:36
@SunilMohanAdapa  deleted the certificate and tried to download my profile found that the< cert> </cert> is empty. so write a new method to add ``` unique_subject = no ``` in ``` index.txt.attr```  as a solution to this ?

**Comment by SunilMohanAdapa** [comment] 2017-03-28 13:15
On 03/28/2017 01:06 PM, Hemanth Kumar Veeranki wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> deleted the
> certificate and tried to download my profile found that the< cert> is
> empty. so write a new method to add |unique_subject = no| in
> |index.txt.attr| as a solution to this ?

Yes, exactly.  This can be done during setup process.  However, perhaps
it is better to do this while generating the user certificate every
time.  Make sure to use augeas for editing the file.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment] 2017-03-29 16:22
This should be fixed now with the merge of #772.

**Closed by SunilMohanAdapa** 2017-03-29 16:22 UTC
Labels: bug
