### ISSUE TITLE
Unable to install applications from Plinth?

### ISSUE THREAD

**Issue by johnfrancismccann** [freedombox/Plinth#1156] opened 2017-11-28 18:53 UTC
So I'm not able to install any applications from the Plinth UI. When trying to install Ejabberd, `/var/log/plinth/status.log` reports

```
[2017-11-28 18:14:42,545] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'install', 'ejabberd', 'ejabberd']
[2017-11-28 18:14:43,395] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[2017-11-28 18:14:46,235] plinth.setup   ERROR    Error running setup - PackageException(error_string="Error during installation", error_details="E: Sub-process /usr/bin/dpkg returned an error code (1)
")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 85, in run
    self.module.setup(self, old_version=current_version)
  File "/usr/local/lib/python3.6/dist-packages/plinth/modules/ejabberd/__init__.py", line 101, in setup
    helper.install(managed_packages)
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 117, in install
    transaction.install()
  File "/usr/local/lib/python3.6/dist-packages/plinth/package.py", line 82, in install
    self.package_names)
  File "/usr/local/lib/python3.6/dist-packages/plinth/package.py", line 105, in _run_apt_command
    raise PackageException(_('Error during installation'), self.stderr)
plinth.package.PackageException: PackageException(error_string="Error during installation", error_details="E: Sub-process /usr/bin/dpkg returned an error code (1)
")
[2017-11-28 18:14:46,917] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']
[2017-11-28 18:14:47,041] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy'], ,
```
The same problem occurs with `['sudo', '-n', '/usr/share/plinth/actions/packages', 'is-package-manager-busy']` when trying to install Roundcube.

Maybe relevant, when I try upgrading software packages from Plinth, the log reports: 

```
2017-11-28 16:53:49,441 INFO Initial blacklisted packages: 
2017-11-28 16:53:49,441 INFO Initial whitelisted packages: 
2017-11-28 16:53:49,441 INFO Starting unattended upgrades script
2017-11-28 16:53:49,441 INFO Allowed origins are: ['origin=Debian', 'origin=Debian,codename=sid,label=Debian-Security']
2017-11-28 16:54:37,582 WARNING Package 'plinth' has conffile prompt and needs to be upgraded manually
2017-11-28 16:54:50,142 INFO package 'plinth' not upgraded
2017-11-28 16:54:55,231 INFO Packages that will be upgraded: apache2 apache2-bin apache2-data apache2-utils apt apt-utils bind9-host binutils binutils-common binutils-x86-64-linux-gnu cpp-6 cpp-7 curl dbus debconf debconf-i18n debianutils dh-strip-nondeterminism dirmngr dnsutils dpkg-dev fakeroot g++-7 gcc-6 gcc-6-base gcc-7 gcc-7-base geoip-database gir1.2-nm-1.0 git git-man gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm gpgv ipset iso-codes libapache2-mod-php7.0 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libapt-pkg5.0 libasan3 libasan4 libatomic1 libbind9-141 libbinutils libc-bin libc-dev-bin libc-l10n libc6 libc6-dev libcc1-0 libcilkrts5 libcups2 libcupsimage2 libcurl3 libdbus-1-3 libdevmapper1.02.1 libdns-export190 libdns190 libdpkg-perl libexpat1 libexpat1-dev libfile-stripnondeterminism-perl libfontconfig1 libgcc-6-dev libgcc-7-dev libgcc1 libgomp1 libgssapi-krb5-2 libipset3 libisc-export189 libisc189 libisccc140 libisccfg144 libitm1 libkrb5-3 libkrb5support0 liblsan0 liblwres141 libmpx2 libmsv1 libncurses5 libncursesw5 libnghttp2-14 libnss3 libpam-systemd libperl5.26 libpython3-dev libpython3-stdlib libquadmath0 libssl1.0.2 libstdc++-7-dev libstdc++6 libsystemd0 libthai0 libtinfo5 libtsan0 libubsan0 libudev1 libwebpdemux2 libwrap0 libxslt1.1 linux-headers-4.13.0-1-amd64 linux-headers-4.13.0-1-common linux-image-4.13.0-1-amd64 linux-libc-dev locales locales-all network-manager nscd perl perl-base perl-modules-5.26 php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline python-cryptography python-django-common python-pkg-resources python-setuptools python3 python3-all python3-cryptography python3-dev python3-django python3-django-axes python3-minimal python3-pkg-resources python3-ruamel.yaml python3-setuptools systemd systemd-sysv tasksel tasksel-data tcpd texlive texlive-base texlive-bibtex-extra texlive-extra-utils texlive-fonts-recommended texlive-formats-extra texlive-lang-greek texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-plain-generic texlive-science texlive-xetex udev vim-common vim-tiny virtualbox-guest-dkms wpasupplicant
2017-11-28 16:54:55,232 INFO Writing dpkg log to '/var/log/unattended-upgrades/unattended-upgrades-dpkg.log'
2017-11-28 16:55:20,676 ERROR Exception happened during upgrade.
NoneType: None
2017-11-28 16:55:20,677 ERROR Exception happened during upgrade.
NoneType: None
2017-11-28 16:55:20,678 ERROR Installing the upgrades failed!
2017-11-28 16:55:20,678 ERROR error message: 'installArchives() failed'
2017-11-28 16:55:20,679 ERROR dpkg returned a error! See '/var/log/unattended-upgrades/unattended-upgrades-dpkg.log' for details

```

And finally, `/var/log/unattended-upgrades/unattended-upgrades-dpkg.log`  reports:

```
Log started: 2017-11-28  16:54:57
(Reading database ... 111932 files and directories currently installed.)
Preparing to unpack .../texlive-latex-extra_2017.20171128-1_all.deb ...
Unpacking texlive-latex-extra (2017.20171128-1) over (2017.20171031-1) ...
Processing triggers for tex-common (6.09) ...
Running mktexlsr. This may take some time... done.
Setting up texlive-latex-extra (2017.20171128-1) ...
Setting up firewalld (0.4.4.6-1) ...
Failed to restart firewalld.service: Transaction contains conflicting jobs 'restart' and 'stop' for fail2ban.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status firewalld.service' for details.
invoke-rc.d: initscript firewalld, action "restart" failed.
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-11-28 16:27:13 UTC; 28min ago
     Docs: man:firewalld(1)
 Main PID: 350 (firewalld)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/firewalld.service
           └─350 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

Nov 28 16:27:09 freedombox systemd[1]: Starting firewalld - dynamic firewall daemon...
Nov 28 16:27:13 freedombox systemd[1]: Started firewalld - dynamic firewall daemon.
Nov 28 16:27:16 freedombox firewalld[350]: WARNING: '/sbin/iptables-restore --wait=2 -n' failed: /sbin/iptables-restore: unrecognized option '--wait=2'
                                           iptables-restore: line 93 failed
Nov 28 16:27:17 freedombox firewalld[350]: ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
Nov 28 16:27:17 freedombox firewalld[350]: ERROR: '/sbin/ebtables -t filter -X FORWARD_direct -P RETURN' failed: No extra options allowed with -X.
Nov 28 16:27:17 freedombox firewalld[350]: ERROR: COMMAND_FAILED
Nov 28 16:27:17 freedombox firewalld[350]: WARNING: '/sbin/iptables-restore --wait=2 -n' failed: /sbin/iptables-restore: unrecognized option '--wait=2'
                                           iptables-restore: line 18 failed
Nov 28 16:27:17 freedombox firewalld[350]: WARNING: '/sbin/ip6tables-restore --wait=2 -n' failed: /sbin/ip6tables-restore: unrecognized option '--wait=2'
                                           ip6tables-restore: line 18 failed
Nov 28 16:27:17 freedombox firewalld[350]: ERROR: COMMAND_FAILED
dpkg: error processing package firewalld (--configure):
 installed firewalld package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.7.6.1-4) ...
Processing triggers for tex-common (6.09) ...
Running updmap-sys. This may take some time... done.
Running mktexlsr /var/lib/texmf ... done.
Errors were encountered while processing:
 firewalld
```

Any thoughts? Any help would be really appreciated.

**Comment by JoKeyser** [comment] 2017-11-28 19:36
Hi @johnfrancismccann , thank you for reporting this issue.

My first guess would be that the root cause of your problem is described in #1133, a conflict between fail2ban and firewalld. In your case, unattended-upgrades couldn't complete because of that, leaving dpkg in a failed state, so you can't install new packages, I guess.
Could you try to `sudo systemctl stop fail2ban` and `apt-get update` to finish the upgrades? Maybe a `dpkg-reconfigure firewalld` is necessary, too?

**Comment by jvalleroy** [comment] 2017-11-28 23:44
Also, it looks like there is a conffile prompt for plinth. If you do "apt-get upgrade" or "apt-get install plinth", it should ask about changes to some file that was installed by plinth.

If it is a file that you edited manually, then it is no problem. But if you didn't edit the file, then this is an issue that should be fixed.

**Comment by johnfrancismccann** [comment] 2017-11-29 01:19
No problem, thanks for the quick reply. Stopping fail2ban worked, and I didn't have to run `dpkg-reconfigure firewalld`.

And when running `apt-get install plinth`, I actually didn't get any conffile prompts. I hadn't edited any files to begin with, so don't know why that showed up as a warning in the upgrades log.

**Comment by JoKeyser** [comment] 2017-11-29 12:51
Okay great, again thanks for filing the issue. I'm closing this as a duplicate of  #1133.

**Closed by JoKeyser** 2017-11-29 12:51 UTC
