### ISSUE TITLE
Let's Encrypt certificate for ejabberd

### ISSUE THREAD

**Issue by bogdanoff** [freedombox/Plinth#1124] opened 2017-11-08 10:35 UTC
Currently the self-signed certificate is used for the jabber server, but it is possible to use the certificate obtained from Let's Encrypt by doing:
`cd /etc/letsencrypt/live/$HOST`
`cat privkey.pem cert.pem chain.pem > /etc/ejabberd/ejabberd.pem`

Apparently this has to be done after each re-obtaining of the certificate.
Does it make sense?

**Comment by JoKeyser** [comment] 2017-11-08 14:40
Hi @bogdanoff , thanks for your idea. The short answer is that this was recently included, see PR #919.
You're right, the tricky part was to re-do this operation for each LE certificate renewal. This is achieved by a renew-hook from certbot.

**Comment by JoKeyser** [comment] 2017-11-08 14:43
Once/if you have the most recent plinth version, you'll have the option at the Let's Encrypt page to activate this feature. The UI for this is currently a bit confusing, but will be automated further, see #1091

**Comment by JoKeyser** [comment] 2017-11-08 14:48
Closing as duplicate of #565, but thanks again, @bogdanoff .

**Closed** 2017-11-08 14:49 UTC
Labels: duplicate
