### ISSUE TITLE
Owncloud on BeagleBoneBlack/freedombox - downloaded files do not open seems corrupt

### ISSUE THREAD

**Issue by renL8** [freedombox/Plinth#399] opened 2016-02-13 18:17 UTC
I use owncloud on beaglebone black running freedombox 0.7. 
Data (particularly videos, pdf and compressed files)  uploaded from any device don't open elsewhere except on itself no matter how it is uploaded (webUI or local directory). Strangely jpg files work. I  observed this problem on freedombox 0.6  and 0.7. Is there a way to fix it?

**Comment by SunilMohanAdapa** [comment] 2016-02-15 03:45
Okay, here is a theory on why this may be happening: small files succeed and larger files fail due to some size handling issues.  Because the full file is available on the device that uploaded it, it opens fine but on other devices, it fails because only partial file is downloaded.

Could you check that this is the case.  To test, upload a file that has failed before.  Download it on another device and check it's size.

**Comment by renL8** [comment] 2016-02-19 12:26
Thank you for looking into the matter. The issue seem to have solved on 
its own after I performed Package Upgrades using freedombox webUI.

**Comment by SunilMohanAdapa** [comment] 2016-02-19 14:07
Thank you for writing back. Since the issue is not reproducible elsewhere, I am closing the issue.  Please feel free to re-open for further discussion.

**Closed by SunilMohanAdapa** 2016-02-19 14:07 UTC
Labels: need-more-info
