### ISSUE TITLE
msgfmt: found 2 fatal errors

### ISSUE THREAD

**Issue by pranaygupta36** [freedombox/Plinth#1068] opened 2017-10-16 20:45 UTC
I am getting this error when i do vagrant provision. (possibly error in ./setup.py install)
`django.core.management.base.CommandError: Execution of msgfmt failed: /vagrant/build/lib/plinth/locale/cs/LC_MESSAGES/django.po:1091: a format specification for argument 'num_lines' doesn't exist in 'msgstr'
==> default: /vagrant/build/lib/plinth/locale/cs/LC_MESSAGES/django.po:1395: a format specification for argument 'box_name' doesn't exist in 'msgstr'
`
can someone please suggest a possible fix.

**Comment by JoKeyser** [comment] 2017-10-16 21:22
Hi @pranaygupta36 , I can't reproduce on current master... but I remember that error from 2 days ago. Maybe you just have to pull again?

**Comment by pranaygupta36** [comment] 2017-10-16 21:53
Thank you @JoKeyser vagrant provision runs successfully now.

**Comment by JoKeyser** [comment] 2017-10-16 22:06
Okay great, then I'll close this. In case you're interested, I fixed the problem in Weblate, it was simply that the strings need to contain the format arguments, see  f70a033.

**Closed by JoKeyser** 2017-10-16 22:06 UTC
