### ISSUE TITLE
VirtualBox: Not able to access HTTP/HTTPS with Firewall activated

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#227] opened 2015-09-09 16:12 UTC
When using a virtualbox v0.5 image I can ping my freedombox, but I can't access the box using http/https. Disabling the firewalld service allows me to connect.

    iptables -L

	Chain INPUT (policy ACCEPT)
	target     prot opt source               destination         
	ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
	ACCEPT     all  --  anywhere             anywhere            
	INPUT_direct  all  --  anywhere             anywhere            
	INPUT_ZONES_SOURCE  all  --  anywhere             anywhere            
	INPUT_ZONES  all  --  anywhere             anywhere            
	ACCEPT     icmp --  anywhere             anywhere            
	DROP       all  --  anywhere             anywhere             ctstate INVALID
	REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

	Chain FORWARD (policy ACCEPT)
	target     prot opt source               destination         
	ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
	ACCEPT     all  --  anywhere             anywhere            
	FORWARD_direct  all  --  anywhere             anywhere            
	FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere            
	FORWARD_IN_ZONES  all  --  anywhere             anywhere            
	FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere            
	FORWARD_OUT_ZONES  all  --  anywhere             anywhere            
	ACCEPT     icmp --  anywhere             anywhere            
	DROP       all  --  anywhere             anywhere             ctstate INVALID
	REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

	Chain OUTPUT (policy ACCEPT)
	target     prot opt source               destination         
	OUTPUT_direct  all  --  anywhere             anywhere            

	Chain FORWARD_IN_ZONES (1 references)
	target     prot opt source               destination         
	FWDI_internal  all  --  anywhere             anywhere            [goto] 
	FWDI_public  all  --  anywhere             anywhere            [goto] 

	Chain FORWARD_IN_ZONES_SOURCE (1 references)
	target     prot opt source               destination         

	Chain FORWARD_OUT_ZONES (1 references)
	target     prot opt source               destination         
	FWDO_internal  all  --  anywhere             anywhere            [goto] 
	FWDO_public  all  --  anywhere             anywhere            [goto] 

	Chain FORWARD_OUT_ZONES_SOURCE (1 references)
	target     prot opt source               destination         

	Chain FORWARD_direct (1 references)
	target     prot opt source               destination         

	Chain FWDI_internal (1 references)
	target     prot opt source               destination         
	FWDI_internal_log  all  --  anywhere             anywhere            
	FWDI_internal_deny  all  --  anywhere             anywhere            
	FWDI_internal_allow  all  --  anywhere             anywhere            

	Chain FWDI_internal_allow (1 references)
	target     prot opt source               destination         

	Chain FWDI_internal_deny (1 references)
	target     prot opt source               destination         

	Chain FWDI_internal_log (1 references)
	target     prot opt source               destination         

	Chain FWDI_public (1 references)
	target     prot opt source               destination         
	FWDI_public_log  all  --  anywhere             anywhere            
	FWDI_public_deny  all  --  anywhere             anywhere            
	FWDI_public_allow  all  --  anywhere             anywhere            

	Chain FWDI_public_allow (1 references)
	target     prot opt source               destination         

	Chain FWDI_public_deny (1 references)
	target     prot opt source               destination         

	Chain FWDI_public_log (1 references)
	target     prot opt source               destination         

	Chain FWDO_internal (1 references)
	target     prot opt source               destination         
	FWDO_internal_log  all  --  anywhere             anywhere            
	FWDO_internal_deny  all  --  anywhere             anywhere            
	FWDO_internal_allow  all  --  anywhere             anywhere            

	Chain FWDO_internal_allow (1 references)
	target     prot opt source               destination         

	Chain FWDO_internal_deny (1 references)
	target     prot opt source               destination         

	Chain FWDO_internal_log (1 references)
	target     prot opt source               destination         

	Chain FWDO_public (1 references)
	target     prot opt source               destination         
	FWDO_public_log  all  --  anywhere             anywhere            
	FWDO_public_deny  all  --  anywhere             anywhere            
	FWDO_public_allow  all  --  anywhere             anywhere            

	Chain FWDO_public_allow (1 references)
	target     prot opt source               destination         

	Chain FWDO_public_deny (1 references)
	target     prot opt source               destination         

	Chain FWDO_public_log (1 references)
	target     prot opt source               destination         

	Chain INPUT_ZONES (1 references)
	target     prot opt source               destination         
	IN_internal  all  --  anywhere             anywhere            [goto] 
	IN_public  all  --  anywhere             anywhere            [goto] 

	Chain INPUT_ZONES_SOURCE (1 references)
	target     prot opt source               destination         

	Chain INPUT_direct (1 references)
	target     prot opt source               destination         

	Chain IN_internal (1 references)
	target     prot opt source               destination         
	IN_internal_log  all  --  anywhere             anywhere            
	IN_internal_deny  all  --  anywhere             anywhere            
	IN_internal_allow  all  --  anywhere             anywhere            

	Chain IN_internal_allow (1 references)
	target     prot opt source               destination         
	ACCEPT     udp  --  anywhere             224.0.0.251          udp dpt:mdns ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain ctstate NEW
	ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:5280 ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:xmpp-server ctstate NEW
	ACCEPT     udp  --  anywhere             anywhere             udp dpt:ntp ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9050 ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:xmpp-client ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https ctstate NEW
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8118 ctstate NEW
	ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps ctstate NEW
	ACCEPT     udp  --  anywhere             anywhere             udp dpt:netbios-ns ctstate NEW
	ACCEPT     udp  --  anywhere             anywhere             udp dpt:netbios-dgm ctstate NEW

	Chain IN_internal_deny (1 references)
	target     prot opt source               destination         

	Chain IN_internal_log (1 references)
	target     prot opt source               destination         

	Chain IN_public (1 references)
	target     prot opt source               destination         
	IN_public_log  all  --  anywhere             anywhere            
	IN_public_deny  all  --  anywhere             anywhere            
	IN_public_allow  all  --  anywhere             anywhere            

	Chain IN_public_allow (1 references)
	target     prot opt source               destination         
	ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW

	Chain IN_public_deny (1 references)
	target     prot opt source               destination         

	Chain IN_public_log (1 references)
	target     prot opt source               destination         

	Chain OUTPUT_direct (1 references)
	target     prot opt source               destination

**Comment by steglicd** [comment] 2015-09-09 18:27
could you please post the output of:
iptables -L -v (note the "-v")
and
ip addr

What IP address are you using to access http/https ?

I assume that input chain is missing the local interface rule.


Are you using eth0 to access http/https? If this is the case, try:
sudo iptables -I INPUT 2 -i eth0 -j IN_internal_allow

this should fix it, the networkmanager connection seems to be not assigned to internal zone?

**Comment by fonfon** [comment] 2015-09-09 18:58
I access my box via the interface `enp0s8`. The command you propose allows me to access the box with the firewall activated:

    iptables -I INPUT 2 -i enp0s8 -j IN_internal_allow

detailed outputs:

    iptables -L -v

	Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
	 pkts bytes target     prot opt in     out     source               destination         
	 4182 3446K ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
	   54  3384 ACCEPT     all  --  lo     any     anywhere             anywhere            
	   64 16280 INPUT_direct  all  --  any    any     anywhere             anywhere            
	   64 16280 INPUT_ZONES_SOURCE  all  --  any    any     anywhere             anywhere            
	   64 16280 INPUT_ZONES  all  --  any    any     anywhere             anywhere            
	    0     0 ACCEPT     icmp --  any    any     anywhere             anywhere            
	    0     0 DROP       all  --  any    any     anywhere             anywhere             ctstate INVALID
	   46 13181 REJECT     all  --  any    any     anywhere             anywhere             reject-with icmp-host-prohibited

	Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
	    0     0 ACCEPT     all  --  lo     any     anywhere             anywhere            
	    0     0 FORWARD_direct  all  --  any    any     anywhere             anywhere            
	    0     0 FORWARD_IN_ZONES_SOURCE  all  --  any    any     anywhere             anywhere            
	    0     0 FORWARD_IN_ZONES  all  --  any    any     anywhere             anywhere            
	    0     0 FORWARD_OUT_ZONES_SOURCE  all  --  any    any     anywhere             anywhere            
	    0     0 FORWARD_OUT_ZONES  all  --  any    any     anywhere             anywhere            
	    0     0 ACCEPT     icmp --  any    any     anywhere             anywhere            
	    0     0 DROP       all  --  any    any     anywhere             anywhere             ctstate INVALID
	    0     0 REJECT     all  --  any    any     anywhere             anywhere             reject-with icmp-host-prohibited

	Chain OUTPUT (policy ACCEPT 3188 packets, 594K bytes)
	 pkts bytes target     prot opt in     out     source               destination         
	 3291  602K OUTPUT_direct  all  --  any    any     anywhere             anywhere            

	Chain FORWARD_IN_ZONES (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDI_public  all  --  enp0s8 any     anywhere             anywhere            [goto] 
	    0     0 FWDI_internal  all  --  enp0s3 any     anywhere             anywhere            [goto] 
	    0     0 FWDI_public  all  --  +      any     anywhere             anywhere            [goto] 

	Chain FORWARD_IN_ZONES_SOURCE (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FORWARD_OUT_ZONES (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDO_public  all  --  any    enp0s8  anywhere             anywhere            [goto] 
	    0     0 FWDO_internal  all  --  any    enp0s3  anywhere             anywhere            [goto] 
	    0     0 FWDO_public  all  --  any    +       anywhere             anywhere            [goto] 

	Chain FORWARD_OUT_ZONES_SOURCE (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FORWARD_direct (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_internal (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDI_internal_log  all  --  any    any     anywhere             anywhere            
	    0     0 FWDI_internal_deny  all  --  any    any     anywhere             anywhere            
	    0     0 FWDI_internal_allow  all  --  any    any     anywhere             anywhere            

	Chain FWDI_internal_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_internal_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_internal_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_public (2 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDI_public_log  all  --  any    any     anywhere             anywhere            
	    0     0 FWDI_public_deny  all  --  any    any     anywhere             anywhere            
	    0     0 FWDI_public_allow  all  --  any    any     anywhere             anywhere            

	Chain FWDI_public_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_public_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDI_public_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_internal (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDO_internal_log  all  --  any    any     anywhere             anywhere            
	    0     0 FWDO_internal_deny  all  --  any    any     anywhere             anywhere            
	    0     0 FWDO_internal_allow  all  --  any    any     anywhere             anywhere            

	Chain FWDO_internal_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_internal_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_internal_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_public (2 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    0     0 FWDO_public_log  all  --  any    any     anywhere             anywhere            
	    0     0 FWDO_public_deny  all  --  any    any     anywhere             anywhere            
	    0     0 FWDO_public_allow  all  --  any    any     anywhere             anywhere            

	Chain FWDO_public_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_public_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain FWDO_public_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain INPUT_ZONES (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	   46 12149 IN_public  all  --  enp0s8 any     anywhere             anywhere            [goto] 
	   16  2979 IN_internal  all  --  enp0s3 any     anywhere             anywhere            [goto] 
	    2  1152 IN_public  all  --  +      any     anywhere             anywhere            [goto] 

	Chain INPUT_ZONES_SOURCE (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain INPUT_direct (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain IN_internal (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	   16  2979 IN_internal_log  all  --  any    any     anywhere             anywhere            
	   16  2979 IN_internal_deny  all  --  any    any     anywhere             anywhere            
	   16  2979 IN_internal_allow  all  --  any    any     anywhere             anywhere            

	Chain IN_internal_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	   16  2979 ACCEPT     udp  --  any    any     anywhere             224.0.0.251          udp dpt:mdns ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:http ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:domain ctstate NEW
	    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:domain ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:5280 ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:xmpp-server ctstate NEW
	    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:ntp ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:9050 ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:xmpp-client ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:ssh ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:https ctstate NEW
	    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:8118 ctstate NEW
	    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:bootps ctstate NEW
	    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:netbios-ns ctstate NEW
	    0     0 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:netbios-dgm ctstate NEW

	Chain IN_internal_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain IN_internal_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain IN_public (2 references)
	 pkts bytes target     prot opt in     out     source               destination         
	   48 13301 IN_public_log  all  --  any    any     anywhere             anywhere            
	   48 13301 IN_public_deny  all  --  any    any     anywhere             anywhere            
	   48 13301 IN_public_allow  all  --  any    any     anywhere             anywhere            

	Chain IN_public_allow (1 references)
	 pkts bytes target     prot opt in     out     source               destination         
	    2   120 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:ssh ctstate NEW

	Chain IN_public_deny (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain IN_public_log (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

	Chain OUTPUT_direct (1 references)
	 pkts bytes target     prot opt in     out     source               destination         

and

    ip addr
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host 
           valid_lft forever preferred_lft forever
    2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 08:00:27:a0:a7:6d brd ff:ff:ff:ff:ff:ff
        inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
           valid_lft 78261sec preferred_lft 78261sec
        inet6 fe80::a00:27ff:fea0:a76d/64 scope link 
           valid_lft forever preferred_lft forever
    3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 08:00:27:3a:4d:47 brd ff:ff:ff:ff:ff:ff
        inet 192.168.56.101/24 brd 192.168.56.255 scope global dynamic enp0s8
           valid_lft 1193sec preferred_lft 1193sec
        inet6 fe80::a00:27ff:fe3a:4d47/64 scope link 
           valid_lft forever preferred_lft forever

**Comment by steglicd** [comment] 2015-09-09 20:22
The Chain INPUT_ZONES, which will be passed for incoming frames has a reference for interface enp0s8 to IN_public. But it should be IN_internal. enp0s3 is IN_internal. 

So it seems like your firstboot script has detected enp0s8 to be WAN and enp0s3 to be LAN.

I tried to reproduce and downloaded virtualbox image. but the firstboot script assigned enp0s3 to external (WAN) and enp0s8 to internal (LAN).

So could you confirm, that your setup produced a config file:
`cat /etc/NetworkManager/system-connections/freedomboxWAN |grep interface`
`interface-name=enp0s8`

and
`cat /etc/NetworkManager/system-connections/freedomboxLAN* |grep interface`
`interface-name=enp0s3`

**Comment by fonfon** [comment] 2015-09-09 20:42
The former works:

    root@freedombox:~# cat /etc/NetworkManager/system-connections/freedomboxWAN |grep interface
    interface-name=enp0s3

But there is no file like `/etc/NetworkManager/system-connections/freedomboxLAN`.

As I think of it I probably have caused the problem by starting the image without much VM network adapter setup, then shutting it down, doing the VM network setup and booting it again. 

If this caused the issue, a note/warning in the VirtualBox documentation might be sufficient (except if solving it is easy), the setup description in the wiki is in the correct order already.

**Comment by steglicd** [comment] 2015-09-09 20:50
Yes. This will explain the behaviour. The firstboot script will assign the first detected network interface to WAN zone and all remaining interfaces to LAN zone. Firstboot script will only run once. So any network interfaces which are attached later will be ignored. So maybe we need a udev script to attach new interfaces to a zone? @sunil ?

**Comment by SunilMohanAdapa** [comment] 2015-09-11 12:42
On 09/10/2015 02:20 AM, Daniel Steglich wrote:
> Yes. This will explain the behaviour. The firstboot script will
> assign the first detected network interface to WAN zone and all
> remaining interfaces to LAN zone. Firstboot script will only run
> once. So any network interfaces which are attached later will be
> ignored.

That is some nice debugging.  I will add a note to VirtualBox
configuration for perhaps Manual/Network page regarding this.

> So maybe we need a udev script to attach new interfaces to a zone?
> @sunil <https://github.com/sunil> ?

That is a nice idea.  I have opened issue #228 to track our discussion
on this.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment] 2015-09-11 13:49
Also, firewalld and network manager zone assignment works quite reliably. So the following commands are what I use at higher level as first point to debug:

```shell
nmcli con
nmcli conn show 'conn_name' | grep zone
firewall-cmd --zone=internal --list-all
firewall-cmd --zone=external --list-all
firewall-cmd --zone=internal --add-interface=eth0
nmcli conn modify 'conn_name' connection.zone internal
```

**Comment by SunilMohanAdapa** [comment] 2015-09-12 17:35
> If this caused the issue, a note/warning in the VirtualBox documentation might be sufficient
> (except if solving it is easy), the setup description in the wiki is in the correct order already.

I have documented the networking behavior and VirtualBox network types in more detail.
https://wiki.debian.org/FreedomBox/Hardware/VirtualBox
https://wiki.debian.org/FreedomBox/Manual/Networks

I believe we can close this issue now.  Please feel free to re-open the issue if there is more to be done.

**Closed by SunilMohanAdapa** 2015-09-12 17:35 UTC
Labels: bug

**Comment by SunilMohanAdapa** [comment] 2015-09-12 17:40
Another idea is to change the default firewall zone assigned to `internal` or `external` instead of public.  I have open another issue for this #229.
