### ISSUE TITLE
Cannot install wiki

### ISSUE THREAD

**Issue by stueja** [freedombox/Plinth#463] opened 2016-05-18 17:38 UTC
Stops with `error during package install: The following packages have unmet dependencies: gcc: Depends: cpp (>= 4:5.3.1-2) but it is not going to be installed Depends: gcc-5 (>= 5.3.1-17~) but it is not going to be installed None `

**Comment by SunilMohanAdapa** [comment] 2016-05-22 17:35
On 05/18/2016 11:08 PM, Jan wrote:
> Stops with |error during package install: The following packages have
> unmet dependencies: gcc: Depends: cpp (>= 4:5.3.1-2) but it is not going
> to be installed Depends: gcc-5 (>= 5.3.1-17~) but it is not going to be
> installed None|
> 

Could you please recheck if the problem is resolved.  It seems to be a
temporary issue with state of packages in Debian unstable.

-- 
Sunil

**Comment by stueja** [comment] 2016-05-23 05:45
As I am not at home and the redirection does not work yet, I ran a manual `apt-get update` via SSH, and got the below mentioned error. Also, I wanted to install nano, which got me strange output. Could this be connected to the wiki installation issue?
```
root@fbx:~# apt-get update
Get:1 http://ftp.nl.debian.org/debian sid InRelease [205 kB]
Get:2 http://mirror.as35701.net/debian sid/main Sources [6,755 kB]
Get:3 http://ftp.nl.debian.org/debian sid/main armhf Packages [6,895 kB]
Get:4 http://mirror.iway.ch/debian sid/main Translation-en [5,361 kB]
Fetched 19.2 MB in 31s (616 kB/s)                                              
Reading package lists... Error!
E: Unable to parse package file /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_i18n_Translation-en (1)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
```
```
root@fbx:~# apt-get install nano
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 ifupdown : Breaks: systemd (< 228-3~) but 228-2 is to be installed
 libpam-systemd : Depends: systemd (= 229-6) but 228-2 is to be installed
 systemd : Depends: libsystemd0 (= 228-2) but 229-6 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

**Comment by SunilMohanAdapa** [comment] 2016-05-23 17:13
This looks like a problem that got introduced during an automatic upgrade.  This is not related to wiki install.  From time to time Debian unstable breaks like this and you seem to have caught it during two bad times.

Please try `apt-get -f install`.  After that you can try `apt-get dist-upgrade`. Then try installing wiki from Plinth interface.

**Comment by stueja** [comment] 2016-05-24 12:44
Well, I think the output does not look too promising. Any additional ideas?
```
root@fbx:~# apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  systemd
Suggested packages:
  systemd-ui systemd-container
The following packages will be upgraded:
  systemd
1 upgraded, 0 newly installed, 0 to remove and 316 not upgraded.
20 not fully installed or removed.
Need to get 3269 kB of archives.
After this operation, 278 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ftp.hawo.stw.uni-erlangen.de/debian sid/main armhf systemd armhf 22                                                                                                                     9-6 [3269 kB]
Fetched 3269 kB in 0s (3562 kB/s)
Setting up adduser (3.114) ...
(Reading database ... 49727 files and directories currently installed.)
Preparing to unpack .../systemd_229-6_armhf.deb ...
Unpacking systemd (229-6) over (228-2) ...
dpkg: warning: unable to delete old directory '/etc/X11/xinit/xinitrc.d': Direct                                                                                                                     ory not empty
dpkg: warning: unable to delete old directory '/etc/X11/xinit': Directory not em                                                                                                                     pty
Setting up systemd (229-6) ...
Installing new version of config file /etc/systemd/logind.conf ...
Installing new version of config file /etc/systemd/resolved.conf ...
Installing new version of config file /etc/systemd/system.conf ...
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Removing obsolete conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh ...
Setting up udev (229-6) ...
addgroup: The group `input' already exists as a system group. Exiting.
update-initramfs: deferring update (trigger activated)
Removing obsolete conffile /etc/modprobe.d/fbdev-blacklist.conf ...
Setting up libnss-myhostname:armhf (229-6) ...
Setting up ifupdown (0.8.11) ...
Installing new version of config file /etc/init.d/networking ...
Created symlink from /etc/systemd/system/multi-user.target.wants/networking.serv                                                                                                                     ice to /lib/systemd/system/networking.service.
Created symlink from /etc/systemd/system/network-online.target.wants/networking.                                                                                                                     service to /lib/systemd/system/networking.service.
Setting up libssl1.0.2:armhf (1.0.2h-1) ...
Setting up libpython3.4-minimal:armhf (3.4.4-3) ...
Setting up libexpat1:armhf (2.1.1-2) ...
Setting up python3.4-minimal (3.4.4-3) ...
Setting up debconf-i18n (1.5.59) ...
Setting up libc-l10n (2.22-9) ...
Setting up libpam-systemd:armhf (229-6) ...
Setting up locales-all (2.22-9) ...
Setting up locales (2.22-9) ...
Installing new version of config file /etc/locale.alias ...
locales-all installed, skipping locales generation
Setting up mime-support (3.60) ...
Installing new version of config file /etc/mime.types ...
Setting up libffi6:armhf (3.2.1-4) ...
Setting up libmpdec2:armhf (2.4.2-1) ...
Setting up libpython3.4-stdlib:armhf (3.4.4-3) ...
Setting up nscd (2.22-9) ...
Setting up python3.4 (3.4.4-3) ...
Processing triggers for dbus (1.10.6-1) ...
Processing triggers for initramfs-tools (0.120) ...
update-initramfs: /boot/initrd.img-4.2.0-1-armmp has been altered.
update-initramfs: Cannot update. Override with -t option.
Processing triggers for libc-bin (2.22-9) ...
Processing triggers for systemd (229-6) ...
[master 4208614] committing changes in /etc after apt run
 Author: box <box@fbx.box.local>
 12 files changed, 68 insertions(+), 14 deletions(-)
 delete mode 100755 X11/xinit/xinitrc.d/50-systemd-user.sh
 create mode 100644 dhcp/dhclient-exit-hooks.d/timesyncd
 create mode 120000 systemd/system/multi-user.target.wants/networking.service
 create mode 120000 systemd/system/network-online.target.wants/networking.servic                                                                                                                     e
======  How can you help?  (doc: https://wiki.debian.org/how-can-i-help ) ======

New packages removed from Debian 'testing' (the maintainer might need help):
 - shaarli - https://tracker.debian.org/pkg/shaarli

-----  Show old opportunities as well as new ones: how-can-i-help --old  -----
```
```
root@fbx:~# apt-get dist-upgrade
Reading package lists... Done
Segmentation faulty tree... 50%
root@fbx:~# apt-get dist-upgrade
Reading package lists... Done
Segmentation faulty tree... 50%
root@fbx:~#

```
```
root@fbx:~# apt-get update
Get:1 http://ftp.halifax.rwth-aachen.de/debian sid InRelease [205 kB]
Get:2 http://ftp.halifax.rwth-aachen.de/debian sid/main Sources [6755 kB]
Get:3 http://ftp.halifax.rwth-aachen.de/debian sid/main armhf Packages [6896 kB]
Get:4 http://ftp.halifax.rwth-aachen.de/debian sid/main Translation-en [5364 kB]
Fetched 19.2 MB in 35s (543 kB/s)
Reading package lists... Error!
E: Unable to parse package file /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_binary-armhf_Packages (1)
E: Unable to parse package file /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_i18n_Translation-en (1)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
root@fbx:~# vi /etc/apt/sources.list
###note: setting from httpredir to a different mirror
root@fbx:~# apt-get update
Get:1 http://ftp.hawo.stw.uni-erlangen.de/debian sid InRelease [205 kB]
Get:2 http://ftp.hawo.stw.uni-erlangen.de/debian sid/main Sources [6755 kB]
Get:3 http://ftp.hawo.stw.uni-erlangen.de/debian sid/main armhf Packages [6896 kB]
Get:4 http://ftp.hawo.stw.uni-erlangen.de/debian sid/main Translation-en [5364 kB]
Fetched 19.2 MB in 35s (544 kB/s)
Reading package lists... Error!
E: Unable to parse package file /var/lib/apt/lists/ftp.hawo.stw.uni-erlangen.de_debian_dists_sid_main_binary-armhf_Packages (1)
E: Unable to parse package file /var/lib/apt/lists/ftp.hawo.stw.uni-erlangen.de_debian_dists_sid_main_i18n_Translation-en (1)
E: Problem syncing the file - sync (5: Input/output error)
E: Problem syncing the file - sync (5: Input/output error)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
```

**Comment by SunilMohanAdapa** [comment] 2016-06-04 18:07
We are seeing some occasional and rare corruptions happing the file system which we are following up [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826345).

@stueja , I recommend you start with a fresh image to get around the problem.  Otherwise, simple delete all the files in /var/lib/apt/lists/ and do a fressh `apt-get update` and `apt-get dist-upgrade`.

I am closing this bug as we will be tracking the other one in freedombox-package.  Please feel free to reopen for more discussion.

**Closed by SunilMohanAdapa** 2016-06-04 18:07 UTC

**Comment by stueja** [comment] 2016-06-05 07:37
Thank you for your reply.
I cleared all the files, nevertheless `apt-get update` fails:
```
root@fbx:/home/box# rm /var/lib/apt/lists/*
rm: cannot remove '/var/lib/apt/lists/partial': Is a directory
root@fbx:/home/box# rm /var/lib/apt/lists/partial/*
root@fbx:/home/box# apt-get update
Get:1 http://mirror.unitedcolo.de/debian sid InRelease [205 kB]
Get:2 http://mirror.unitedcolo.de/debian sid/main Sources [6,818 kB]
Get:3 http://mirror.unitedcolo.de/debian sid/main armhf Packages [6,902 kB]
Get:4 http://mirror.unitedcolo.de/debian sid/main Translation-en [5,378 kB]                                                                          
Fetched 19.3 MB in 32s (590 kB/s)                                                                                                                    
Reading package lists... Error!
E: Unable to parse package file /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_binary-armhf_Packages (1)
E: Unable to parse package file /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_i18n_Translation-en (1)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
``` 
`cat /var/lib/apt/lists/httpredir.debian.org_debian_dists_sid_main_binary-armhf_Packages | less` outputs a lot of `^@`
