### ISSUE TITLE
synapse: can't login to huge rooms 

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#1029] opened 2017-09-28 14:17 UTC
I can't join #ubuntu via riot on my synapse server (on a Raspberry Pi 2). People in #riot suggested my server may not be able to handle an enormous room. Is there something to it? I'm curious since I'm the only user on that server and  rooms with 4000 users seem to work fine.

First I have to wait until the first search results appear

![image](https://user-images.githubusercontent.com/164785/30967908-e366efee-a45d-11e7-86e1-98d961b235ca.png)

Then i can finally chose #ubuntu 
![image](https://user-images.githubusercontent.com/164785/30967968-0e40886a-a45e-11e7-816b-f66bcae089c1.png)

but after a long wait...
![image](https://user-images.githubusercontent.com/164785/30967988-1f5627d6-a45e-11e7-8a62-b31e8f6bfa4d.png)

...I get this error:
![image](https://user-images.githubusercontent.com/164785/30968012-3118c726-a45e-11e7-9823-104370bbfa59.png)

**Comment by mray** [comment] 2017-09-28 14:18
Trying to join #ubuntu via Polari says 
```
[#ubuntu-unregged] You have been redirected to a notice-only channel because the channel you tried to join 1) has a lot of join attempts right now, or 2) is limited to NickServ-identified users for anti-spam reasons. If trying to join again does not work, identify to NickServ. If you don't have a NickServ account, see /msg nickserv help register and /join #freenode with any questions.
```

... is it possible that synapse (and therefore riot) can't handle this situation and just says 503?

**Comment by JoKeyser** [comment] 2017-09-30 17:14
I can confirm with my own RPi2 - and most likely it's simply a lack of RAM. Before trying to join #ubuntu, I see ~350 MiB used in `htop`. During the attempt to join, synapse ramps up to use ALL remaining RAM and CPU shoots to 100%, until it breaks down and the error message above is shown:
![synapsefullram](https://user-images.githubusercontent.com/8722846/31047908-a07298c2-a602-11e7-9241-f910fdc2401c.png)


Quoting https://github.com/matrix-org/synapse/blob/master/README.rst, which includes a possible remedy (that I haven't tried):
> Requreiments: At least 1GB of free RAM if you want to join large public rooms like #matrix:matrix.org
and 
> Synapse's architecture is quite RAM hungry currently - we deliberately cache a lot of recent room data and metadata in RAM in order to speed up common requests. We'll improve this in future, but for now the easiest way to either reduce the RAM usage (at the risk of slowing things down) is to set the almost-undocumented SYNAPSE_CACHE_FACTOR environment variable. The default is 0.5, which can be decreased to reduce RAM usage in memory constrained enviroments, or increased if performance starts to degrade.

**Comment by JoKeyser** [comment] 2017-10-29 16:08
Here an update, since I now believe my comments were misleading in two ways.

First, I think failure to join #ubuntu might have a different reason, as I get errors `Could not join #ubuntu on 'chat.freenode.net': err_needreggednick`. The fact that the RAM runs wildly overboard may just be a phenomenon on top of the actual problem with the non-registered nickname.

Second, I experimented with SYNAPSE_CACHE_FACTOR. Unlike suggested in the citation above, the current default is not (yet) 0.5 but 0.1, at least in my current Debian install. (The devs have updated that since upstream. One can check by grepping for the relevant lines with `grep -R os.environ /usr/lib/python2.7/dist-packages/synapse/`.) In the posts over at https://github.com/matrix-org/synapse/pull/612 suggest "roughly speaking, a SYNAPSE_CACHE_FACTOR of 1.0 will max out at around 3-4GB [of RAM ...] 0.1 probably around ~700MB, and 0.02  targets roughly ~512MB".
In Debian, one can comfortably set that variable in `/etc/default/matrix-synapse`.
After that make sure to `sudo systemctl daemon-reload` (dunno if necessary) and `sudo systemctl restart matrix-synapse`. I've tried various entries from 0.001 to 0.1 while trying to join the matrix.org's Riot room (just under 5000 users), but to no avail - I always get a ETIMOUTED error.

**Comment by JoKeyser** [comment] 2017-10-29 16:58
@mray given that you're able to join rooms with ~4000 users, and #ubuntu only has about ~2500, I now think this issue isn't only about room size. And even if it was, there doesn't seem to be much we can do, short of waiting for a more efficient server app - [Matrix Dendrite](https://github.com/matrix-org/dendrite) is supposed to solve this, as far as I'm informed. So I'm inclined to close this issue as "wontfix" here, if you agree?

**Comment by mray** [comment] 2017-10-29 17:13
I agree. We better let other people solve this one. As long as it isn't about a wrong configuration but hardware and software limitations it isn't our ballpark imho.

**Comment by JoKeyser** [comment] 2017-10-29 17:32
Okay, let's close this one for now, but keep it in mind in case Synapse gets more efficiency options or upgrades.

**Closed by JoKeyser** 2017-10-29 17:32 UTC

**Comment by JoKeyser** [comment] 2017-11-01 20:34
Correction about myself not able to join the very large Riot room (4500 people): It *did* work in the end, after several hours, to join. However since this attempt (after days), one of my Pi2's cpu's is more or less constantly at 100%. I estimate that RAM usage of Synapse is around 350 MiB, system is now at ~650 MiB out of 1 GiB. All updating in several Riot clients to my server is incredibly slow, pretty unusable (several minutes). Not sure whether this is a bug in Synapse or the expected behavior. Could be related to https://github.com/matrix-org/synapse/issues/1899, but that's also pretty vague.

**Comment by JoKeyser** [comment] 2017-11-13 10:35
Addendum: With new hardware (4GB RAM) and setting `SYNAPSE_CACHE_FACTOR = 1`, everything is noticeably faster, though joining large rooms still takes more tens-of-minutes/hours(?) than I cared to time properly. Joining Riot (4500 users), Linux (3500) and MatrixHQ (11000) uses about 1.2 GB RAM (system is now at 1.4GB total, Matrix as only active service).
So overall, RAM doesn't seem the only bottleneck to fast & fluid performance. I should compare with an account at Matrix.org sometime, to have a reference.

**Comment by JoKeyser** [comment] 2017-11-26 11:32
Post-addendum: Yesterday I [migrated Synapse's database from SQLite to PostgreSQL](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst). That significantly improved performance again, maybe more so than having more RAM. Now scrolling in even huge rooms stops for only ~1s, often less. RAM use seems lowered by about 0.5 GB too, now system is at 1.4 GB, even after joining 2-3 additional (smaller) rooms. Overall, moving to Postgres seems more important than having huge amounts of RAM (and moving to SSD storage instead of SD probably helped, too).
