### ISSUE TITLE
When accesing from outside -> Forbidden: You don't have permission to access /plinth on this server.

### ISSUE THREAD

**Issue by kalakrumanov** [freedombox/Plinth#896] opened 2017-07-08 18:58 UTC
I finally managed to install and configure correctly dynamicDNS, and when I access from outside my network (typing the url that I configured in gnudip.datasystems24.net) I get the following error:

![screen shot 2017-07-08 at 8 50 27 pm](https://user-images.githubusercontent.com/16352883/27988311-5bf7fdec-641f-11e7-92cc-21188b7ba96c.png)

And below I see: 

> Apache/2.4.25 (Debian) Server at my-dynamicdns Port 80

I type the url, and it redirects to /plinth (which is correct) and then comes the error. It only happens in this directory, because when I access to my-dynamicdns/transmission, it works like a charm. Or even when I type my-dynamicdns/index.html it shows me:

![screen shot 2017-07-08 at 8 54 42 pm](https://user-images.githubusercontent.com/16352883/27988322-adb56520-641f-11e7-8ff7-4f48450f9ef2.png)

I haven't changed anything in the config files of apache. 

PD: The TOR version works perfect -> It shows the Plinth correctly (except for partially showing the page, [as I said here](https://github.com/freedombox/Plinth/issues/894))

Cheers!

**Comment by mray** [comment] 2017-07-08 20:17
If I remember correctly it is a safety measure that access to plinth is restricted to "local" access only by default. Not 100% sure though.

**Comment by JoKeyser** [comment] 2017-07-09 14:36
Hi @kalakrumanov , as @mray says, it might be that your box discriminates "internal" from "external" connections, the latter without permissions to access Plinth. That's not a bug but a security feature, as long as it's true that you have an "internal" network... can you describe how your box is connected a bit more?

**Comment by kalakrumanov** [comment] 2017-07-09 18:32
Yes, it looks exactly as a security feature. I have my raspberry pi 1, on ethernet cable.

**Comment by JoKeyser** [comment] 2017-07-09 19:08
Okay, so it's not an actual issue? That is, do you have your RPi1 connected to a router, and you can access Plinth via the internal connection just fine?

**Comment by kalakrumanov** [comment] 2017-07-09 21:02
Yes, via internal I can access correctly, and via remote through TOR also everything works great, except for the "semi-blank" of the webpage, as I wrote here: 

https://github.com/freedombox/Plinth/issues/894

Thanks for your answers @JoKeyser and @mray  ;)

**Comment by JoKeyser** [comment] 2017-07-09 22:01
Okay great, then we can focus on the other issue, and you could close this one, @kalakrumanov .

**Closed** 2017-07-09 22:04 UTC
