### ISSUE TITLE
R Pi2

### ISSUE THREAD

**Issue by clhamlin10** [freedombox/Plinth#448] opened 2016-04-28 19:16 UTC
OpenVPN: Got error 500 - "nothing you can do about it".

**Comment by jvalleroy** [comment] 2016-04-30 18:41
Could you please check for errors in /var/log/plinth/status.log? There should be a python exception at the end of the log file, after you get error 500.

**Comment by SunilMohanAdapa** [comment] 2016-06-04 16:40
This seems to be duplicate of #459 .  I have provided workaround to the problem.  The core issue will be fixed with #456 .

**Closed by SunilMohanAdapa** 2016-06-04 16:40 UTC
Labels: duplicate
