### ISSUE TITLE
Error obtaining letsencrypt certificate

### ISSUE THREAD

**Issue by saghul** [freedombox/Plinth#407] opened 2016-02-17 20:07 UTC
On latest plinth release (0.8.1):

~~~~
2016-02-17 20:05:32,327:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-02-17 20:05:32,339:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-02-17 20:05:32,349:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.0
2016-02-17 20:05:32,350:DEBUG:letsencrypt.cli:Arguments: ['--agree-tos', '--register-unsafely-without-email', '--domain', 'qXXXXXXXX.onion', '--authenticator', 'webroot', '--webroot-path', '/var/www/html/', '--renew-by-default']
2016-02-17 20:05:32,357:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-02-17 20:05:32,392:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2016-02-17 20:05:32,397:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /var/www/html/.well-known/acme-challenge
2016-02-17 20:05:32,399:DEBUG:letsencrypt.display.ops:Single candidate plugin: * webroot
Description: Webroot Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0xb5fc2e90>
Prep: True
2016-02-17 20:05:32,408:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0xb5fc2e90> and installer None
2016-02-17 20:05:32,476:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.0', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1987, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 690, in obtain_cert
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 206, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 191, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 108, in register
    logger.warn("Registering without email!")
  File "/usr/lib/python2.7/logging/__init__.py", line 1171, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/log.py", line 64, in emit
    self.width + self.PADDING_WIDTH)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 2675, in infobox
    kwargs)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
PythonDialogBug
~~~~

**Comment by agropper** [comment] 2016-02-17 20:27
This is what I did for Let's Encrypt for plinth 0.7.1 and it worked very nicely: https://github.com/HIEofOne/PersonalAS/wiki/Milestone-0:--Install-FreedomBox-as-a-%245-mo-Digital-Ocean-droplet 

Give the above procedure, how would I try to test Let's Encrypt on 0.8.1 ?

**Comment by saghul** [comment] 2016-02-17 20:33
The latest plinth release (0.8.1) is available in the official Debian Sid repositories, so you can just dist-upgrade.

**Comment by agropper** [comment] 2016-02-18 02:08
Apologies for the newbie question, but when in the process do I do: sudo apt-get dist-upgrade ?
I did this on an VM that had plinth 0.7.1 running and now ssh times out although I can login via the console. How do I get ssh running again and recover?

**Comment by SunilMohanAdapa** [comment] 2016-02-18 02:58
On 02/18/2016 07:38 AM, Adrian Gropper wrote:
> Apologies for the newbie question, but when in the process do I do: sudo
> apt-get dist-upgrade ?

We can do this anytime.  Another way is to enable automatic upgrades and
they will be installed at night (don't use manual upgrade button in
Plinth 0.7.1, it is somewhat broken).

> I did this on an VM that had plinth 0.7.1 running and now ssh times out
> although I can login via the console. How do I get ssh running again and
> recover?

- Check that SSH server is running.

$ systemctl status ssh

● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor
preset: enabled)
   Active: active (running) since Thu 2016-02-18 02:49:47 UTC; 2min 22s ago
  Process: 1219 ExecReload=/bin/kill -HUP $MAINPID (code=exited,
status=0/SUCCESS)
 Main PID: 655 (sshd)
      CPU: 100ms
   CGroup: /system.slice/ssh.service
           └─655 /usr/sbin/sshd -D

Feb 18 02:49:51 freedombox-vm1 systemd[1]: Reloaded OpenBSD Secure Shell
server.
Feb 18 02:49:51 freedombox-vm1 sshd[655]: Server listening on 0.0.0.0
port 22.
Feb 18 02:49:51 freedombox-vm1 sshd[655]: Server listening on :: port 22.

- Check that firewall is not blocking ssh.

$ firewall-cmd --list-all-zones

...
internal (active)
  ...
  services: ... ssh ...
  ...
external (active)
  ...
  services: ... ssh ...
  ...

- Sometimes virtual machines misbehave and don't allow traffic properly.
 With VirtualBox, a shutdown of the VM and starting again sometimes
fixes NAT port related issues for me.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment] 2016-02-18 03:02
On 02/18/2016 01:37 AM, Saúl Ibarra Corretgé wrote:
> 20:05:32,350:DEBUG:letsencrypt.cli:Arguments: ['--agree-tos',
> '--register-unsafely-without-email', '--domain', 'qXXXXXXXX.onion',
> '--authenticator', 'webroot', '--webroot-path', '/var/www/html/',
> '--renew-by-default'] 2016-02-17

You are trying to obtain a certificate for an .onion domain.  This is
now a special use TLD that Let's Encrypt plans to support in furture.
As of now, they don't issue certificates for .onion addresses yet.

Plinth shows a graceful error on UI that there was an error obtaining
certificate.  The stack trace you posted is weird.

-- 
Sunil

**Comment by saghul** [comment] 2016-02-18 08:12
> You are trying to obtain a certificate for an .onion domain. This is now a special use TLD that Let's Encrypt plans to support in furture. As of now, they don't issue certificates for .onion addresses yet.

The only domain that is listed in Plinth for me is the .onion domain, so I guess that's a bug then and they should be skipped until letsencrypt supports them. I also don't see a way to add any new domain for which to obtain the certs.

> Plinth shows a graceful error on UI that there was an error obtaining certificate. The stack trace you posted is weird.

This is all Plinth shows me:

~~~~
Failed to obtain certificate for domain qXXXX.onion: An unexpected error occurred: PythonDialogBug Please see the logfiles in /var/log/letsencrypt for more details. 
~~~~

What I pasted in the file in /var/log. What's weird about that trace? I'm running an up to date FB on a BBB, with Plinth installed from the repos.

**Comment by SunilMohanAdapa** [comment] 2016-02-18 16:14
When I try to obtain a certificate on onion address, it says:
> Failed to obtain certificate for domain XXXXXXXXX.onion: An unexpected error occurred: The request message was malformed :: Error creating new authz :: Name does not end in a public suffix Please see the logfiles in /var/log/letsencrypt for more details. 

I guessed that, your error message only comes up first time (when there is no account auto-registered it). However, when I start with a fresh /etc/letsencrypt directory, I could not reproduce the problem.  In your case, letsencrypt is trying to show a log message as a dialog (for unknown reason).  Try running the command on the shell and see what happens.

**Comment by agropper** [comment] 2016-02-18 17:02
(apologies for mixing up issues of plinth upgrade with this thread)
As @SunilMohanAdapa suggested, I turned on Automatic Upgrades last night but all I got was:
"You are running Plinth version 0.7.2."

**Comment by saghul** [comment] 2016-02-19 09:55
> (apologies for mixing up issues of plinth upgrade with this thread)

Please open a new issue or send an email to the mailing list.

**Comment by saghul** [comment] 2016-02-19 10:13
@SunilMohanAdapa I made a patch for this in https://github.com/freedombox/Plinth/pull/410

**Comment by SunilMohanAdapa** [comment] 2016-02-26 08:59
#410 is merged, closing this issue.

@agropper , if the upgrade has not happened yet, please contact me via email or IRC.

**Closed by SunilMohanAdapa** 2016-02-26 08:59 UTC
